### ISSUE TITLE
Blender addon can not be installed in 2.79

### ISSUE THREAD

**Issue by IPv6** [martijnberger/pyslapi#21]
With latest Blender i get "DLL import" errors on each start // Reinstall gives following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Main\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 32, in <module>
    from . import sketchup
ImportError: cannot import name 'sketchup'
```

and addon is not activatable... Its a pity, import worked great!

**Comment by Bibi56** [comment]
Are you under Win32? No problem with Win 8.1 64.

**Comment by IPv6** [comment]
Win 10

**Comment by andreimd87** [comment]
well, first you need the sketchup to be installed on system :)

**Comment by IPv6** [comment]
@andreimd87 I already had it installed, of course.

Just for the sake of completeness - just reinstalled SkpPro-64, then downloaded latest zip from this hub -> repacked sketchup_imported (to be able add it as addon) -> started Blender (2.79 master), added addon... same error. Can not enable it, "cannot import name 'sketchup'" at "from . import sketchup"

**Comment by andreimd87** [comment]
maybe you have some other user addons that may conflict with it. try to disable them first and install importer

**Comment by IPv6** [comment]
@andreimd87 no, according to error it surely not the case here. unfortunately

**Comment by SolidFoxZX** [comment]
Blender 2.79 - work ok
Blender 2.79.2 current build - not install. Cheked on win7 and win10

**Comment by martijnberger** [comment]
https://github.com/martijnberger/pyslapi/releases/tag/0.20 is the final release for 2.79b 

next up is making this work with 2.82
